version: "3.8"

services:
  # nginx:
  #   image: nginx:1.25
  #   # build: ./nginx-conf
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./nginx/conf/prod.conf:/etc/nginx/conf.d/default.conf
  #     - ./out/skincareagents.com_ecc:/etc/nginx/ssl
  frontend:
    ports:
      - 443:443
    build:
      context: .
    # image: nodejs
    # container_name: nodejs
    # restart: unless-stopped
    # environment:
      # - API_HOST=http://backend:8000
      # - API_HOST=http://nginx
      # - API_DOMAIN=127.0.0.1
    # depends_on:
    #   - nginx
